language: node_js
node_js:
- '0.10'
env:
  global:
  - GIT_COMMITTER_NAME=elasticsearch-kr
  - GIT_AUTHOR_NAME=Elasticsearch Korea
  - secure: TIEQYnmcmhiRzugZTakARuIiRjV9kNi8DpUBXr0HFHXgw7OGcRLep7vgrGiEplIAfo164zvZVs84kXv1aTYys9Yb9rA8mG2qVg9w1cU86B1BXOFQAGeZOmdfCEemRTH1YvdQJ9rFMGZp+Z6N95XXP9IdoMoljD9DPvb1j3tNm8Y=
before_script:
- npm install -g bower
- npm install -g docpad
- npm install
- bower install
- git remote add target https://$GH_TOKEN@github.com/elasticsearch-kr/elasticsearch-kr.github.io.git
script: docpad deploy-ghpages --env static
